### ISSUE TITLE
[BUG] There is no clever_flamingo_v2.json file

### ISSUE THREAD

**Issue by dylee-softeye** [ChenDelong1999/instruct-flamingo#1]
Hello,

Thank you for your great work.

I attempted to run this project locally and noticed that the "clever_flamingo_v2.json" file is missing from the "open_flamingo/instruction_tuning/tuning_config/" directory. Could you please add this file?

Thank you in advance!

**Comment by ChenDelong1999** [comment]
Hi,

Sorry for missing the config file. The `clever_flamingo_v2.json` is the same as [open_flamingo/instruction_tuning/tuning_config/lora[lm+xqttn]+perceiver.json](https://github.com/ChenDelong1999/instruct-flamingo/blob/main/open_flamingo/instruction_tuning/tuning_config/lora%5Blm%2Bxqttn%5D%2Bperceiver.json), please use this.

Best,
Delong
